name: Sheets Automations

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sheets_changed]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    # Make secrets visible to every step in the job
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Sanity check env
        run: |
          echo "Has SPREADSHEET_ID? $([[ -n \"$SPREADSHEET_ID\" ]] && echo yes || echo no)"
          # Show only length, not the value
          echo "SPREADSHEET_ID length: ${#SPREADSHEET_ID}"
          # Confirm GOOGLE_SERVICE_ACCOUNT_JSON is present (masked)
          echo "Has GOOGLE_SERVICE_ACCOUNT_JSON? $([[ -n \"$GOOGLE_SERVICE_ACCOUNT_JSON\" ]] && echo yes || echo no)"

      - name: Run automations
        run: node index.js
