name: Sheets Automations

on:
  push:                # runs whenever you push to main
    branches:
      - main
  schedule:            # runs every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:   # still allows manual run from Actions tab

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
