name: Sheets Automations

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sheets_changed]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    # <-- Set env at the JOB level so every step sees them
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Sanity check env
        run: |
          if [ -z "$SPREADSHEET_ID" ]; then
            echo "SPREADSHEET_ID is NOT set"; exit 1
          fi
          echo "SPREADSHEET_ID length: ${#SPREADSHEET_ID}"

      - name: Run automations
        run: node index.js
